//Code is auto generated by VTool
//using System;
//using System.Collections.Generic;
//using System.ComponentModel;
//using System.Data;
//using System.Drawing;
//using System.Text;
//using System.Windows.Forms;
//using NV.ERP..ENT;
//using NV.ERP.CommonCCL;

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

namespace VTool
{
	public partial class Form3 : Form
    {
		public  Form3()
		{
            InitializeComponent();
        }
    }
}
